name = "hugo-three4th"
license = "MIT"
licenselink = "https://github.com/Jacob953/hugo-three4th/blob/master/LICENSE"
description = "A digital garden theme for hugo"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/Jacob953/hugo-three4th"

# If you have a running demo of the theme.
demosite = "https://jacob953.com"

display = ["note", "essay", "blog", "illustration"]
status = ["sow", "grow", "mature"]

# If the theme has a single author
[author]
    name = "Jacob953"
    homepage = "https://github.com/Jacob953"
