baseURL = 'https://example.org/'
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0  International License."
languageCode = "en-us"
title = "Three4Th"
theme = "hugo-three4th"

[author]
  name = "Three4Th"
  email = "i@jacob953.com"
  intro = "aaa qkjdhakjsd askjdh akjd hakjs"
  role = "aaa"

[params] 
  subscribe = true
  [[params.extLink]]
    name = "github"
    url = "https://github.com/Jacob953/hugo-three4th"

[menu]
  [[menu.main]]
    name = "Garden"
    url = "/"
    weight = 1
    post = "caret-down"
  [[menu.main]]
    name = "Essays"
    url = "/essays"
    parent = "Garden"
    weight = 1
  [[menu.main]]
    name = "Lanes"
    url = "/lanes"
    parent = "Garden"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library"
    parent = "Garden"
    weight = 3
  [[menu.main]]
    name = "Releases"
    url = "/cassette"
    weight = 2
  [[menu.main]]
    name = "Wiki"
    url = "https://github.com/Jacob953/hugo-three4th/wiki"
    weight = 3
    post = "link"
